name: CI

on: { push: ~ }

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: none, curl, dom, mbstring, tokenizer, xml, xmlwriter
      - run: composer update
      - run: composer verify
